name: Build native library (Linux aarch64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-java@v6
        with:
          java-version: '25'
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Build
        run: ./gradlew buildCollectMatch

      - name: Test
        run: ./gradlew test

      - uses: actions/upload-artifact@v7
        with:
          name: native-linux-aarch64
          path: src/main/resources/native/linux/aarch64/

  commit:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7

      - uses: actions/download-artifact@v8
        with:
          name: native-linux-aarch64
          path: src/main/resources/native/linux/aarch64/

      - name: Check for changes
        id: diff
        run: |
          git add src/main/resources/native/
          git diff --staged --quiet || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push
        if: steps.diff.outputs.changed == 'true'
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "chore: update compiled native libraries"
          git push
